name: 3D Contribution Graph

on:
  schedule:
    - cron: "0 18 * * *"   # chạy mỗi ngày 1:00 AM ICT
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create settings file
        run: |
          cat > /tmp/settings.json << 'EOF'
          {
            "githubUserName": "HuyRakn",
            "type": "GitHubNight",
            "fileName": "profile-night-rainbow.svg"
          }
          EOF

      - name: Generate 3D Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SETTING_JSON: /tmp/settings.json

      - name: Commit and push generated SVG
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "update 3D contribution graph" || exit 0
          git push
